/** Movvo ERP — official color tokens (M-1). */
export const movvoColorsDark = {
  primary: '#D90429',
  primaryHover: '#F01D3F',
  primaryDark: '#A0031F',
  secondary: '#D4AF37',
  secondaryLight: '#F4D35E',
  background: '#080808',
  surface: '#131313',
  card: '#1A1A1A',
  border: '#2B2B2B',
  text: '#FFFFFF',
  muted: '#A1A1AA',
  success: '#22C55E',
  warning: '#F59E0B',
  error: '#EF4444',
  info: '#3B82F6',
  chart: {
    revenue: '#D4AF37',
    checkins: '#D90429',
    finance: '#EF4444',
    workouts: '#F4D35E',
  },
} as const;

export const movvoColorsLight = {
  primary: '#D90429',
  primaryHover: '#F01D3F',
  primaryDark: '#A0031F',
  secondary: '#B8962E',
  secondaryLight: '#D4AF37',
  background: '#F7F7F8',
  surface: '#FFFFFF',
  card: '#FFFFFF',
  border: '#E4E4E7',
  text: '#18181B',
  muted: '#71717A',
  success: '#16A34A',
  warning: '#D97706',
  error: '#DC2626',
  info: '#2563EB',
  chart: {
    revenue: '#B8962E',
    checkins: '#D90429',
    finance: '#EF4444',
    workouts: '#D4AF37',
  },
} as const;

/** @deprecated Use movvoColorsDark — alias for transition sprint */
export const movvoColorsLegacy = {
  red: movvoColorsDark.primary,
  redHover: movvoColorsDark.primaryHover,
  redDark: movvoColorsDark.primaryDark,
  gold: movvoColorsDark.secondary,
  goldLight: movvoColorsDark.secondaryLight,
  background: movvoColorsDark.background,
  surface: movvoColorsDark.surface,
  card: movvoColorsDark.card,
  text: movvoColorsDark.text,
  muted: movvoColorsDark.muted,
  border: movvoColorsDark.border,
  navbar: movvoColorsDark.background,
  inputBg: movvoColorsDark.surface,
  inputBorder: '#333333',
  success: movvoColorsDark.success,
  successHover: '#16A34A',
  danger: movvoColorsDark.primaryDark,
  dangerHover: '#5C000E',
  chart: movvoColorsDark.chart,
} as const;

export const movvoColorsLegacyLight = {
  red: movvoColorsLight.primary,
  redHover: movvoColorsLight.primaryHover,
  redDark: movvoColorsLight.primaryDark,
  gold: movvoColorsLight.secondary,
  goldLight: movvoColorsLight.secondaryLight,
  background: movvoColorsLight.background,
  surface: movvoColorsLight.surface,
  card: movvoColorsLight.card,
  text: movvoColorsLight.text,
  muted: movvoColorsLight.muted,
  border: movvoColorsLight.border,
  navbar: movvoColorsLight.surface,
  inputBg: movvoColorsLight.surface,
  inputBorder: '#D4D4D8',
  success: movvoColorsLight.success,
  successHover: '#15803D',
  danger: movvoColorsLight.primaryDark,
  dangerHover: '#5C000E',
  chart: movvoColorsLight.chart,
} as const;
