import type { SystemRoleSlug } from '../types';

export const PERMISSION_CODES = [
  'dashboard.read',
  'students.read',
  'students.create',
  'students.update',
  'students.delete',
  'finance.read',
  'finance.create',
  'finance.update',
  'finance.export',
  'finance.pay',
  'finance.refund',
  'finance.reconcile',
  'finance.reports',
  'crm.manage',
  'users.read',
  'users.create',
  'users.update',
  'users.delete',
  'roles.read',
  'roles.manage',
  'audit.read',
  'sales.read',
  'sales.create',
  'sales.update',
  'sales.delete',
  'sales.pipeline',
  'sales.contracts',
  'sales.plans',
  'operations.read',
  'operations.create',
  'operations.update',
  'operations.delete',
  'operations.checkin',
  'operations.access',
  'operations.configure',
  'workouts.read',
  'workouts.create',
  'workouts.update',
  'workouts.delete',
  'exercises.read',
  'exercises.manage',
  'assessments.read',
  'assessments.create',
  'assessments.update',
  'progress.read',
  'progress.create',
  'ai.suggest',
  'ai.chat',
  'notifications.read',
  'notifications.send',
  'messaging.read',
  'messaging.send',
  'campaigns.read',
  'campaigns.manage',
  'loyalty.read',
  'loyalty.manage',
  'engagement.read',
  'analytics.read',
  'analytics.manage',
  'reports.read',
  'reports.create',
  'reports.export',
  'reports.schedule',
  'predictions.read',
  'predictions.run',
  'executive.read',
  'ai.insights',
  'platform.read',
  'platform.manage',
  'platform.webhooks',
  'marketplace.read',
  'marketplace.manage',
  'integrations.read',
  'integrations.manage',
  'settings.read',
  'settings.update',
  'backup.create',
] as const;

export type PermissionCode = (typeof PERMISSION_CODES)[number];

export const SYSTEM_ROLES: { slug: SystemRoleSlug; name: string }[] = [
  { slug: 'super_admin', name: 'Super Admin' },
  { slug: 'admin', name: 'Administrador' },
  { slug: 'manager', name: 'Gerente' },
  { slug: 'reception', name: 'Recepcionista' },
  { slug: 'finance', name: 'Financeiro' },
  { slug: 'trainer', name: 'Professor' },
  { slug: 'personal', name: 'Personal' },
  { slug: 'student', name: 'Aluno' },
];
