import {
  Activity,
  ArrowDownUp,
  Banknote,
  BarChart3,
  Building2,
  Calendar,
  CheckCircle2,
  ClipboardList,
  CreditCard,
  Download,
  Dumbbell,
  FileSpreadsheet,
  HeartPulse,
  HelpCircle,
  House,
  LayoutDashboard,
  LogOut,
  ScrollText,
  Settings,
  Shield,
  Sparkles,
  User,
  UserCog,
  Users,
  Wallet,
  Package,
  ShoppingCart,
  Store,
  type LucideIcon,
} from 'lucide-react';

/** Semantic nav / product icons → Lucide. */
export const movvoIcons = {
  dashboard: House,
  student: User,
  students: Users,
  trainer: UserCog,
  sales: Sparkles,
  finance: Wallet,
  cash: Banknote,
  receivables: CreditCard,
  payables: ArrowDownUp,
  subscriptions: ClipboardList,
  agenda: Calendar,
  operations: Calendar,
  checkin: CheckCircle2,
  workouts: Dumbbell,
  assessments: HeartPulse,
  analytics: BarChart3,
  reports: LayoutDashboard,
  bi: BarChart3,
  exports: Download,
  spreadsheet: FileSpreadsheet,
  settings: Settings,
  engagement: Activity,
  users: Users,
  roles: Shield,
  health: HeartPulse,
  logs: ScrollText,
  audit: ScrollText,
  help: HelpCircle,
  profile: User,
  logout: LogOut,
  admin: Building2,
  inventory: Package,
  pdv: ShoppingCart,
  store: Store,
} as const satisfies Record<string, LucideIcon>;

export type MovvoIconName = keyof typeof movvoIcons;

export function getMovvoIcon(name: MovvoIconName): LucideIcon {
  return movvoIcons[name];
}
